#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend dom-frontend
        bind *:80
        mode http
        default_backend benson-backend

backend dom-backend
        balance roundrobin
        server 86242-web-01 52.3.249.183:80 check
        server 86242-web-02 54.237.6.171:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
