#!/usr/bin/env bash
# This loop prints "Best School" 10 times

i="1"
while [ "$i" -lt 10 ]
do
    echo "Best School"
    i=$(( "$i" + 1 ))

    if [ "$i" -eq 9 ]
    then
        echo "Hi"
    fi
done
