#!/usr/bin/env bash
#Creating a script that uses while and case statements
x="1"
while [ $x -le 20 ]
do
    case $x in 
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    echo "$x"
    ((x++))
    
done
